module.exports = {
  'ADD_ROUTE': 'ADD_ROUTE',
  'DELETE_ROUTE': 'DELETE_ROUTE',
  'ARM_ROUTE': 'ARM_ROUTE',
  'DISARM_ROUTE': 'DISARM_ROUTE',
  'MONITOR_ROUTE': 'MONITOR_ROUTE',
  'STOP_MONITORING_ROUTE': 'STOP_MONITORING_ROUTE',
  // perhaps 'ENABLE_SEQUENCER' : 'ENABLE_SEQUENCER',
}